name: Main workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build DataDisplay
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\" 
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Projects\datadisplay.vcxproj
        
    - uses: actions/upload-artifact@v1
      with:
        name: DataDisplay
        path: Result/DataDisplay.exe
        
    - name: Build DataGenerator
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\" 
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Projects\datagenerator.vcxproj
        
    - uses: actions/upload-artifact@v1
      with:
        name: DataGenerator
        path: Result/DataGenerator.exe
